wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1638755334
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.12
      5: 0.12.7
      8:
      - 5
amp:
  desc: null
  value: true
batch_size:
  desc: null
  value: 1
epochs:
  desc: null
  value: 3
img_scale:
  desc: null
  value: 1.0
learning_rate:
  desc: null
  value: 1.0e-05
save_checkpoint:
  desc: null
  value: true
val_percent:
  desc: null
  value: 0.1
